spring:
  profiles:
    active: local
  batch:
    job:
      name: ${job.name:NONE}
    #      enabled: false
    jdbc:
      initialize-schema: never
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/null_shinsa_product?allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&cacheDefaultTimezone=false
    username: root
    password: alsdud6038
    driver-class-name: com.mysql.cj.jdbc.Driver
    p6spy:
      enabled: true
      appender: com.p6spy.engine.spy.appender.Slf4JLogger
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
      use_sql_comments: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: false
        default_batch_fetch_size: 100
    open-in-view: false
#
#  decorator:
#    datasource:
#      p6spy:
#        enable-logging: true
